# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  # Generic boot configuration for USB installer with AMD Ryzen support
  boot.initrd.availableKernelModules = [ 
    "xhci_pci"      # USB 3.0/3.1 controllers
    "ahci"           # SATA controllers
    "ohci_pci"       # USB 1.1 controllers
    "ehci_pci"       # USB 2.0 controllers
    "sd_mod"         # Generic SCSI disk driver
    "sdhci_pci"      # SD card readers (common in laptops)
    "nvme"           # NVMe SSD support (essential for modern systems)
    "usb_storage"     # USB mass storage support
    "usbhid"         # USB human interface devices (keyboards, mice)
    "thunderbolt"     # Thunderbolt support (common on modern laptops)
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ 
    "kvm-amd"        # AMD virtualization support (for Ryzen AI processors)
    "kvm-intel"       # Intel virtualization support (for compatibility)
  ];
  boot.extraModulePackages = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s20f0u1u4u4.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  # CPU microcode support for both Intel and AMD
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
